### ISSUE TITLE
Async module loading fails with `Unhandled Rejection (LinkError)`

### ISSUE THREAD

**Issue by cimi** [ballercat/wasm-loader#5]
I am trying to load a module as instructed in the documentation:

```javascript
import makeTapestry from './wasm/tapestry.wasm';

// [...]

makeTapestry().then(Tapestry => {
  // [...]
});
```
This fails when trying to resolve the promise:

> Unhandled Rejection (LinkError): Import #0 module="env" function="DYNAMICTOP_PTR" error: global import must be a number

```
  14 |     'table': new Table({initial: 0, element: 'anyfunc'})
  15 |   }
  16 | }) {
> 17 |   return instantiate(buffer, deps);
  18 | }
  19 | 
  20 | module.exports = WebAssemblyModule;
```

Here is the build command I use to generate the wasm:

```bash
em++ --bind --std=c++11 -O3 tapestry.cpp -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE=1 -o tapestry.js
```

Is the problem because of the way I am building the module? The js file specified as output exports a module I've been able to successfully use  to interact with the wasm. I was hoping that by using the wasm loader I could eliminate the need for generating that file.

```javascript
import TapestryModule from './wasm/tapestry.js';
// [...]
TapestryModule({wasmBinaryFile: 'wasm/tapestry.wasm'}).then(Tapestry => {
  // Tapestry has the exported C++ functions bound to it
```

**Comment by ballercat** [comment]
Hi,

It's not a problem with your build or the loader. It's just a missing WebAssembly module dependency. I would re-read the error string once more because it's telling you that the module is expecting a dependency which you failed to provide.

Luckily, the `makeTapestry()` function takes a `deps` parameter which you can use to override the default dependencies and provide the missing pieces.

Background:
emscripten when compiling WebAssembly modules will add the wrapper `.js` file to make sure that many things(like `stdlib`) are transpiled and available. This polyfilling of C features comes at the cost of a giant JavaScript file along side the wasm module. 

This loader does no such thing. Giving you the flexibility to decide on how and why you add dependencies, this is what I wanted for my wasm code and why I wrote the loader.

I do think there needs to be some better documentation somewhere about this, maybe even in this repo, but I hope this helped!

**Comment by Flourad** [comment]
I have the same problem.Can i require the glue js  file or config the deps to solve the problem and how to config it in webpack?

**Comment by ballercat** [comment]
Hello @Flourad 

> Can i require the glue js file

If you built your `.wasm` file with emscripten I would recommend using their JavaScript glue code and _not_ the loader. This is especially true if you compiled from C/C++/Rust etc. because those languages need a fair bit of "glue" code to make the wasm output execute.

> config the deps to solve the problem and how to config it in webpack?

You can! But `deps` are supplied at run-time not build-time(webpack). You may supply any number of dependencies to the factory method. I outlined the details in the README. Keep in mind you will need to know what dependencies the module requires.
